### PR TITLE
GEOPY-205: build minimal environment and lock dependencies

### PR DESCRIPTION
**Pull request by sebhmg**
**GEOPY-205 - conda pack for geoapps**

### CODE REVIEW

**Comment by sebhmg** [comment]
pack:simpeg

**Comment by sebhmg** [comment]
pack:simpeg

**Comment by sebhmg** [comment]
any comment

**Comment by sebhmg** [comment]
test comment

**Comment by sebhmg** [comment]
test again

**Comment by sebhmg** [comment]
test comment

**Comment by sebhmg** [comment]
test

**Comment by sebhmg** [comment]
test

**Review by domfournier — DISMISSED** [review]
Can't say I understand what's happening here, but well done.

**Pull request merged**
