### PR TITLE
GEOPY-937: update lock files to pointing to mira-omf 3.0.0-rc.4

### PR DESCRIPTION
**Pull request by sebhmg**
**GEOPY-937 - lock files still pointing to mira-omf 3.0.0-rc3 instead of rc.4**

### CODE REVIEW

**Review by domfournier — COMMENTED** [review]
Di you forget to commit the pyproject.toml?

**Comment by sebhmg** [comment]
> Did you forget to commit the pyproject.toml?

it is only locking. the pyproject says it wants at least 3.0.0-rc.3 and a compatible version

**Review by domfournier — APPROVED** [review]
aight

**Comment by sebhmg** [comment]
BTW, this loose versioning (instead of strict omf 3.0.0-rc.3) in the pyproject.toml allows to patch an existing installation with 3.0.0 or 3.0.0-rc without conflicting  with the constrains expressed by geoapps

**Pull request merged**
